version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-rphub
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rphub
      MYSQL_PASSWORD: pass
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
